spring:
  datasource:
    data: classpath:db/data.sql
    schema: classpath:db/schema.sql
    driver-class-name: org.h2.Driver
    url: jdbc:h2:D:\JavaProgram\H2Database/demo;MODE=MySql;DB_CLOSE_DELAY=-1
    username: root
    password: root
    sql-script-encoding: utf-8
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
